### ISSUE TITLE
Remove unused dependencies from projects and solutions

### ISSUE THREAD

**Issue by melody-universe** [oops-i-git-it-again/sln-crawl#1]

**Comment by cpendery** [comment]
Just writing some notes here about my current research on the topic.

How do we determine that a dependency is unused within a project or solution? For **PackageReferences**'s, they could be used implicitly without a specific name reference. The best example is the `Microsoft.NET.Test.Sdk` which is never used explicitly in a `using` directive. While this might be the case for packages, for ease of use, I believe this isn't the current case for **ProjectReference**'s. 

As a result, we'd be able to `audit/clean` a folder's projects and solutions by ensuring that for the current folder at least 1 `*.cs* file contains a `using` directive for that dependency
